update publishing and checks

diff --git a/.github/workflows/checks.yml b/.github/workflows/checks.yml
--- a/.github/workflows/checks.yml
+++ b/.github/workflows/checks.yml
@@ -21,11 +21,16 @@ jobs:
           cache: 'gradle'
       - name: Setup Chrome
         uses: browser-actions/setup-chrome@v1.7.2
-
       - name: Run Js tests
-        run: ./gradlew jsBrowserTest --warn
+        run: ./gradlew jsBrowserTest --warn --continue
       - name: Run Wasm tests
-        run: ./gradlew wasmJsBrowserTest --warn
+        run: ./gradlew wasmJsBrowserTest --warn --continue
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure()
+        with:
+          report_paths: '**/build/test-results/**/TEST-*.xml'
+          check_name: 'JS JUnit Test Report'
   Checks-Jvm:
     runs-on: ubuntu-latest
     steps:
@@ -41,6 +46,12 @@ jobs:
         run: ./gradlew :library:testDebugUnitTest --warn --continue
       - name: Run Jvm tests
         run: ./gradlew :library:jvmTest --warn --continue
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '**/build/test-results/**/TEST-*.xml'
+          check_name: 'JVM JUnit Test Report'
   Checks-Apple:
     runs-on: macos-latest
     steps:
@@ -54,3 +65,9 @@ jobs:
           cache: 'gradle'
       - name: Run Apple tests
         run: ./gradlew :library:iosSimulatorArm64Test --warn --continue
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '**/build/test-results/**/TEST-*.xml'
+          check_name: 'Apple JUnit Test Report'
